use quiche::ConnectionId;

use crate::QuicResult;

/// A customizable generator to derive and verify QUIC connection IDs.
///
/// For QUIC servers, it can be useful to encode additional information in the
/// source connection ID. This trait allows users to implement their own logic
/// for that purpose. The crate also provides [`SimpleConnectionIdGenerator`]
/// if no such customization is needed.
///
/// Clients currently can't configure a [`ConnectionIdGenerator`] and always use
/// the [`SimpleConnectionIdGenerator`].
pub trait ConnectionIdGenerator<'a>: Send + 'static {
    /// Creates a new [`ConnectionId`] according to the generator's logic.
    ///
    /// The `socket_cookie` is propagated unchanged from the
    /// [`QuicListener`](crate::socket::QuicListener) that received the connection.
    fn new_connection_id(&self, socket_cookie: u64) -> ConnectionId<'a>;

    /// Verifies whether `cid` was generated by this [`ConnectionIdGenerator`].
    ///
    /// `socket_cookie` matches the value that would have been passed to
    /// `new_connection_id` calls. The method should return an [`Err`] variant
    /// if the connection ID can't be verified.
    fn verify_connection_id(&self, socket_cookie: u64, cid: &ConnectionId) -> QuicResult<()>;
}

/// A [`ConnectionIdGenerator`] which creates random 20-byte connection IDs.
///
/// Random bytes are pulled directly from the operating system to create an ID.
/// Any `socket_cookie` value is ignored.
#[derive(Debug, Clone, Default)]
pub struct SimpleConnectionIdGenerator;

impl ConnectionIdGenerator<'static> for SimpleConnectionIdGenerator {
    fn new_connection_id(&self, _socket_cookie: u64) -> ConnectionId<'static> {
        use ring::rand::SecureRandom;

        let mut buf = vec![0; 20];
        let rng = ring::rand::SystemRandom::new();

        rng.fill(&mut buf).unwrap();

        ConnectionId::from_vec(buf)
    }

    /// Performs no verification, because this generator can create
    /// any valid connection ID.
    fn verify_connection_id(&self, _socket_cookie: u64, _cid: &ConnectionId<'_>) -> QuicResult<()> {
        Ok(())
    }
}
