[package]
name = "http3bin-client"
version = "0.1.0"
authors = ["Lucas Pardue <lucaspardue.24.7@gmail.com>"]
edition = "2018"

[dependencies]
docopt = "1"
env_logger = "0.6"
mio = "0"
url = "1"
log = "0"
ring = "0.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
quiche = { path = "../../"}